[package]
name = "aristotle"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph_rasterizer = "0.1.8"
dirs = "5.0.1"
quick-xml = "0.37"
serde = { version = "1.0.217", default-features = false, features = ["derive"] }
softbuffer = { version = "0.4.5", default-features = false, features = ["kms", "wayland"] }
toml = "0.8.19"
tracing = "0.1.40"
tracing-subscriber = "0.3"
ttf-parser = "0.25"
winit = { version = "0.30.5", default-features = false, features = ["rwh_06",
"wayland"] }
zip = { version = "2.2.0", default-features = false, features = ["deflate"] }

