[package]
name = "aristotle"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph_rasterizer = "0.1.8"
quick-xml = "0.37"
# softbuffer = { version = "0.4.5", default-features = false, features = ["kms", "wayland"] }
softbuffer = { version = "0.4.5" }
tracing = "0.1.40"
tracing-subscriber = "0.3"
ttf-parser = "0.25"
# winit = { version = "0.30.5", default-features = false, features = ["rwh_06",
# "wayland"] }
winit = { version = "0.30.5" }
zip = { version = "2.2.0", default-features = false, features = ["deflate"] }

