on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: install dependencies
        run: sudo apt update && sudo apt install libwayland-dev
      - run: cargo check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: install dependencies
        run: sudo apt update && sudo apt install libwayland-dev
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings
