[package]
name = "epub"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = "0.36.2"
tracing = "0.1.40"
zip = { version = "2.2.0", default-features = false, features = ["deflate"] }

[dev-dependencies]
tracing-subscriber = "0.3"
